version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: directory_scanner_backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: directory_scanner_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
